Metamask accounts with portal
futureversecom/trn-substrate-portal pull request #14
Opened 2023-02-09 07:00 UTC by KarishmaBothara

Detail - Use the accounts visited on metamask extension on portal. Possibly giving warning to switch extension account for portal account.

2023-02-10 00:37 UTC, ken-centrality reviewed
Looks good so far, few nitpicks around the code arrangements. Please make sure our changes are stay within the same code block, that way we can rebase things easier in the future.

Also, I see an oppontunity here to use a custom hook for the common code (setState, useEffect) within the Account components, so your changes in each file can be drawn down to a single file.

2023-02-10 00:37 UTC, ken-centrality commented on packages/apps/src/Root.tsx
> +import { metaMaskConnectors } from '../../react-hooks/src/useMetaMask';
nitpick, can we use `@polkadot/react-hooks` import style here? similar to line 13

2023-02-10 00:37 UTC, ken-centrality commented on packages/apps/src/Root.tsx
> +    <Web3ReactProvider connectors={[metaMaskConnectors as any]}>
best to bring Web3ReactProvider below the Suspense

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-accounts/src/Accounts/Account.tsx
> +  }, [wallet.account, connectWallet]);
do we need `wallet.account` dependency here?

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-accounts/src/modals/Transfer.tsx
> +  const [addressError, setAddressError] = useState<string | null>(null);
```suggestion
  const [metaMaskAddressError, setMetaMaskAddressError] = useState<string | null>(null);
```

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-accounts/src/modals/Transfer.tsx
> +  const { wallet } = useMetaMask();
```suggestion
  const { wallet: metaMaskWallet } = useMetaMask();
```

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-extrinsics/src/Submission.tsx
> +  }, [accountId]);
```suggestion
   setIsMetaMask(isMetaMaskAccSelected);
  }, [accountId]);
```

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-extrinsics/src/Submission.tsx
> +          isMetaMask={isMetaMask}
why does the generic TxButton needs to know it's a MetaMask?

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-staking/src/Actions/Account/BondExtra.tsx
> +
let's make sure all of our changes in different files are in one single block like this, will help with the rebasing in the future

2023-02-10 00:37 UTC, ken-centrality commented on packages/page-staking/src/Actions/partials/Bond.tsx
> +      setIsMetaMask(false);
ditto

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-api/src/Api.tsx
> +  console.log('wallet::', wallet);
```suggestion
```

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-api/src/Api.tsx
> +      injectedAccounts.push(({ address: acc, meta: { name: `MetaMask_${acc}`, source: 'isMetaMask', whenCreated: Date.now() } }));
```suggestion
      injectedAccounts.push(({ address: acc, meta: { name: `${acc} (MetaMask)`, source: 'isMetaMask', whenCreated: Date.now() } }));
```

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-api/src/Api.tsx
> +    if (wallet.account) {
```suggestion
    if (!wallet.account) return
```

return early @KarishmaBothara, don't forget 😉

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-api/src/Api.tsx
> +      const metaMaskAcc: string[] = localStore.get('METAMASK_STORAGE_KEY') || [];
use `METAMASK_ACCOUNTS` as key, it's more descriptive

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-api/src/Api.tsx
> +            .catch(console.error);
hmm this might not work, you would need `console.error.bind(console)`, I could be wrong

2023-02-10 00:37 UTC, ken-centrality commented on packages/react-components/src/InputAddress/index.tsx
> +  isMetaMask?: boolean
do we need this?

2023-02-10 00:39 UTC, ken-centrality commented
![Screenshot 2023-02-10 at 13 34 32](https://user-images.githubusercontent.com/97480229/217970925-b8d7d239-1aed-430f-9a30-b2d0bb7d2518.png)

A) Let's remove this, in the future, we might want to add a small copy about MetaMask
B) Should there be a button here to add account from MetaMask?

2023-02-10 03:57 UTC, KarishmaBothara commented on packages/apps/src/Root.tsx
> +import { metaMaskConnectors } from '../../react-hooks/src/useMetaMask';
Yes, I did try it with @polkadot/react-hooks, however ended up with error in build as below
<img width="1284" alt="Screenshot 2023-02-10 at 7 56 54 AM" src="https://user-images.githubusercontent.com/29415595/217997003-876c8b1c-09d6-49f8-9be6-5f4d15684fb2.png">

2023-02-10 05:47 UTC, KarishmaBothara commented on packages/page-extrinsics/src/Submission.tsx
> +  }, [accountId]);
can't do it like setIsMetaMask(isMetaMaskAccSelected);
isMetaMaskAccSelected gives the selected element.. however updated the code to
setIsMetaMask(isMetaMaskAccSelected ? true : false);

2023-02-10 05:49 UTC, KarishmaBothara commented on packages/page-extrinsics/src/Submission.tsx
> +          isMetaMask={isMetaMask}
So that it can sign the extrinsic via metamask if the account selected is metamask account.

2023-02-10 05:58 UTC, KarishmaBothara commented on packages/react-components/src/InputAddress/index.tsx
> +  isMetaMask?: boolean
no.. thanks for spotting this!!

2023-02-10 05:59 UTC, KarishmaBothara commented
> ![Screenshot 2023-02-10 at 13 34 32](https://user-images.githubusercontent.com/97480229/217970925-b8d7d239-1aed-430f-9a30-b2d0bb7d2518.png)
> 
> A) Let's remove this, in the future, we might want to add a small copy about MetaMask B) Should there be a button here to add account from MetaMask?

A) Yes, will remove in subsequent PR
B) Added a button to connect to MetaMask

2023-02-12 20:49 UTC, ken-centrality requested changes
Getting there, a few more UI changes

![Screenshot 2023-02-13 at 09 36 25](https://user-images.githubusercontent.com/97480229/218335831-77092d86-8ce7-4fd3-b8ea-07ff14144039.png)

A) Replace the `polkadot-js extension`  with MetaMask extension and link it to Google Chrome. You can also remove the last paragraph ("Since some extensions...")
B) Can we remove this?
C) Can we remove this? As looks like there are no available actions here
D) Can we change the display format here to be similar to MetaMask (0x123...1234), and the second smaller text can be a full address (no uppercase). And the this should be applied to the account dropdown too if possible.

2023-02-12 20:49 UTC, ken-centrality commented on packages/page-accounts/src/modals/Transfer.tsx
> +      setMetaMaskAddressError(`Please select ${propSenderId} in your MetaMask wallet`);
```suggestion
      setMetaMaskAddressError(`Please select ${propSenderId} in your MetaMask wallet to sign this extrinsic. Or select the current active account in the dropdown`);
```

2023-02-13 06:24 UTC, KarishmaBothara commented
> Getting there, a few more UI changes
> 
> ![Screenshot 2023-02-13 at 09 36 25](https://user-images.githubusercontent.com/97480229/218335831-77092d86-8ce7-4fd3-b8ea-07ff14144039.png)
> 
> A) Replace the `polkadot-js extension` with MetaMask extension and link it to Google Chrome. You can also remove the last paragraph ("Since some extensions...") B) Can we remove this? C) Can we remove this? As looks like there are no available actions here D) Can we change the display format here to be similar to MetaMask (0x123...1234), and the second smaller text can be a full address (no uppercase). And the this should be applied to the account dropdown too if possible.

Addressed

2023-02-14 02:48 UTC, ken-centrality commented
@KarishmaBothara can you please resolve the build issue

2023-02-14 04:11 UTC, KarishmaBothara commented
> @KarishmaBothara can you please resolve the build issue

sorry for that.. did not notice.. will fix it nw

2023-02-14 08:30 UTC, ken-centrality approved these changes

2023-02-14 08:46 UTC, merged